apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: application-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: application-service
    app.kubernetes.io/part-of: application-service
  name: application-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: application-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: application-service
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-has-tenant/application-service/application-service@sha256:4c96a141353a15ac7d8484151095b18355f60b02a62f18cc1604274836797b55
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 6060
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
