apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: application-service
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-has-tenant/application-service/application-service@sha256:26cd62cbb015a6f48fa2c5b61d34229182b72a2ccb87c478f9da7406ad735c2e
        name: container-image
        resources: {}
status: {}
