apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: application-service
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-has-tenant/application-service/application-service@sha256:f2910705b5df034c36f826af71532c26e9a83d8bcbe0784e38ba961d3ee21a8f
        name: container-image
        resources: {}
status: {}
