apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: application-service
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-has-tenant/application-service/application-service@sha256:8d5380e3ecf4803eca5612e4089882682cacc74847a807a31f29e3565e006470
        name: container-image
        resources: {}
status: {}
